### ISSUE TITLE
Pass HttpClient to AuthressClient

### ISSUE THREAD

**Issue by pwiejak** [Authress/authress.sdk.cs#4]
It would be great to have the option to pass or configure HttpClient to AuthressClient, so there's a way to configure some retry policy etc.

**Comment by wparad** [comment]
Hey @pwiejak, I assume #5 would solve your issue, this way you could customize the base message handler and perform different actions in a custom message handler. Since HttpClient is pretty empty, it seemed way more configurable this way. Let me know if that wouldn't work for your use case.

**Comment by pwiejak** [comment]
Hi @wparad 
Thanks for quick response, I think that should also work.

**Comment by wparad** [comment]
Okay, let's go with this then, and if it isn't sufficient we can try adding something else. I would be curious in the resulting configuration, it could be a good example to add to the repo.

**Comment by pwiejak** [comment]
@wparad it works like a charm :)
I'm using following handler to add retry policy, it's injected to IHttpClientHandlerFactory implementation that simply returns it in the Create method:

    ` 
    public class RetryHandler : HttpClientHandler
    {
        private readonly AsyncRetryPolicy _policy;

        public RetryHandler()
        {
            _policy = Policy.Handle<HttpRequestException>()
                .WaitAndRetryAsync(5, attempt => TimeSpan.FromMilliseconds(new Random().Next(300, 1000)));
        }

        protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var policyResult = await _policy.ExecuteAndCaptureAsync(() => InternalSendAsync(request, cancellationToken));

            if(policyResult.Outcome == OutcomeType.Failure)
            {
                throw policyResult.FinalException;
            }

            return policyResult.Result;
        }

        private async Task<HttpResponseMessage> InternalSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var response = await base.SendAsync(request, cancellationToken);

            return (int)response.StatusCode != StatusCodes.Status429TooManyRequests
                ? response
                : throw new HttpRequestException(StatusCodes.Status429TooManyRequests.ToString());
        }
    }
`

For the policy I'm using Polly.

**Comment by wparad** [comment]
Awesome, thanks for sharing.
